spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PointOfSale
    username: postgres
    password: DataBeta
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host : 127.0.0.1
    port : 6379
